name = "foruca"
compatibility_date = "2025-04-11"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[env.staging.observability]
enabled = true
head_sampling_rate = 100
